// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkccpvqudildgkgnffpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrY2NwdnF1ZGlsZGdrZ25mZnB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNDcwNjcsImV4cCI6MjA2OTYyMzA2N30.NPqWo0XavsJqmEh94WGRxLZ9feqFgPTwfcsKXRZFCYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});